# docker-compose up -d
# docker-compose down -v
version: "3.8"
services:
  b-shop-redis:
    container_name: b-shop-redis
    image: redis:6.2.7
    environment:
      - TZ=Asia/Seoul
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
  b-shop-database:
    container_name: b-shop-database
    image: mysql:8.0.31
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - TZ=Asia/Seoul
    volumes:
      - ./database/config:/etc/mysql/conf.d
    ports:
      - ${DB_PORT}:3306
  b-shop-minio:
    container_name: b-shop-minio
    image: quay.io/minio/minio
    volumes:
      - minio_storage:/data
    ports:
     - ${MINIO_PORT}:9000
     - ${MINIO_WEB_PORT}:9001
    environment:
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
    command: server --console-address ":9001" /data
  create_bucket:
    container_name: create-bucket
    image: minio/mc
    depends_on:
      - b-shop-minio
    entrypoint: >
      /bin/sh -c "
      mc config host add minio http://b-shop-minio:${MINIO_WEB_PORT} ${MINIO_USER} ${MINIO_PASSWORD};
      mc mb minio/${MINIO_BUCKET};
      mc anonymous set public minio/${MINIO_BUCKET};
      "

volumes:
  minio_storage: {}
