# docker-compose up -d
# docker-compose down -v
version: "3.8"
services:
  b-shop-redis:
    container_name: b-shop-redis
    image: redis:6.2.7
    environment:
      - TZ=Asia/Seoul
    ports:
      - ${REDIS_PORT}:6379
  b-shop-database:
    container_name: b-shop-database
    image: mysql:8.0.31
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - TZ=Asia/Seoul
    volumes:
      - ./database/config:/etc/mysql/conf.d
    ports:
      - ${DB_PORT}:3306
