server:
  port: ${SERVER_PORT}

spring:
  profiles:
    active: ${ACTIVE_PROFILE}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}
    properties:
      hibernate:
        hibernate.default_batch_fetch_size: ${FETCH_SIZE}
      jakarta:
        persistence:
          sharedCache:
            mode: ALL
    open-in-view: false
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

---
server:
  local:
    domain: ${LOCAL_DOMAIN}
  prod:
    domain: ${PROD_DOMAIN}
    url: ${PROD_URL}

  default:
    profile-image-url: ${PROFILE_IMAGE_URL}
    item-image-url: ${ITEM_IMAGE_URL}

cart:
  expired-time: ${CART_EXPIRED_TIME}

hiworks:
  client:
    id: ${CLIENT_ID}
    secret: ${CLIENT_SECRET}
  url:
    accessToken: ${ACCESS_TOKEN_URL}
    user: ${USER_URL}

token:
  access-expired-time: ${ACCESS_EXPIRED_TIME}
  refresh-expired-time: ${REFRESH_EXPIRED_TIME}
  secret: ${TOKEN_SECRET}

minio:
  endpoint: ${MINIO_ENDPOINT}
  user: ${MINIO_USER}
  password: ${MINIO_PASSWORD}
  bucket: ${MINIO_BUCKET}

shedlock:
  table: shedlock

sentry:
  dsn: ${SENTRY_DSN}
  exception-resolver-order: -2147483647
  traces-sample-rate: 1.0

logging:
  level:
    org:
      hibernate:
        SQL: ${LOG_LEVEL}
