spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bshop_db
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        hibernate.default_batch_fetch_size: 100
      jakarta:
        persistence:
          sharedCache:
            mode: ALL
    open-in-view: false
  data:
    redis:
      host: 127.0.0.1
      port: 6379
---
logging:
  level:
    org:
      hibernate:
        SQL: debug
---
hiworks:
  client:
    id: hiworks-client-id
    secret: hiworks-client-secret
  url:
    accessToken: https://api.hiworks.com/open/auth/accesstoken
    user: https://api.hiworks.com/user/v2/me

token:
  access-expired-time: 123456789
  refresh-expired-time: 123456780
  secret: abcdefghijklmnopqrstuv.secret.key