server:
  port: ${SERVER-PORT}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB-URL}
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}
    properties:
      hibernate:
        hibernate.default_batch_fetch_size: 100
      jakarta:
        persistence:
          sharedCache:
            mode: ALL
    open-in-view: false
  data:
    redis:
      host: ${REDIS-HOST}
      port: 6379
---
logging:
  level:
    org:
      hibernate:
        SQL: debug
---
hiworks:
  client:
    id: ${CLIENT-ID}
    secret: ${CLIENT-SECRET}
  url:
    accessToken: ${ACCESSTOKEN-URL}
    user: ${USER-URL}


token:
  access-expired-time: ${ACCESS-EXPIRED-TIME}
  refresh-expired-time: ${REFRESH-EXPIRED-TIME}
  secret: ${TOKEN-SECRET}